services:
  cms:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kyu-cms
    restart: unless-stopped
    ports:
      - "3202:1337"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    network_mode: bridge
    enable_ipv6: true
    env_file:
      - .env
    environment:
      - NODE_ENV=production

