services:
  cms:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kyu-cms
    restart: unless-stopped
    ports:
      - "3202:1337"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    # Enable IPv6 support (requires Docker daemon IPv6 enabled)
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    env_file:
      - .env
    environment:
      - NODE_ENV=production

